main_arm_SIM/compliance_controller:
  type: velocity_controllers/ComplianceController #position_controllers/JointTrajectoryController velocity_controllers/JointTrajectoryController effort_controllers/JointTrajectoryController velocity_controllers/ComplianceController
  topic: "test_ur5e_SIM"
  compliance_command_timeout: 1.5
  joints:
     - bvr_SIM/main_arm_SIM/shoulder_pan_joint
     - bvr_SIM/main_arm_SIM/shoulder_lift_joint
     - bvr_SIM/main_arm_SIM/elbow_joint
     - bvr_SIM/main_arm_SIM/wrist_1_joint
     - bvr_SIM/main_arm_SIM/wrist_2_joint
     - bvr_SIM/main_arm_SIM/wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      bvr_SIM/main_arm_SIM/shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      bvr_SIM/main_arm_SIM/shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      bvr_SIM/main_arm_SIM/elbow_joint: {trajectory: 0.1, goal: 0.1}
      bvr_SIM/main_arm_SIM/wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      bvr_SIM/main_arm_SIM/wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      bvr_SIM/main_arm_SIM/wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 20
# Customization - From: https://github.com/ros-industrial/ur_modern_driver/blob/6b818fa149bcd070131d6b04e5d97e2f67d28684/config/ur5_controllers.yaml
  gains:
      #!!These values have not been optimized!!
      bvr_SIM/main_arm_SIM/shoulder_pan_joint:  {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
      bvr_SIM/main_arm_SIM/shoulder_lift_joint: {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
      bvr_SIM/main_arm_SIM/elbow_joint:         {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
      bvr_SIM/main_arm_SIM/wrist_1_joint:       {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
      bvr_SIM/main_arm_SIM/wrist_2_joint:       {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
      bvr_SIM/main_arm_SIM/wrist_3_joint:       {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
# Use a feedforward term to reduce the size of PID gains
  velocity_ff:
      bvr_SIM/main_arm_SIM/shoulder_pan_joint: 1.0
      bvr_SIM/main_arm_SIM/shoulder_lift_joint: 1.0
      bvr_SIM/main_arm_SIM/elbow_joint: 1.0
      bvr_SIM/main_arm_SIM/wrist_1_joint: 1.0
      bvr_SIM/main_arm_SIM/wrist_2_joint: 1.0
      bvr_SIM/main_arm_SIM/wrist_3_joint: 1.0
# Customization - From: https://github.com/ros-industrial/ur_modern_driver/blob/6b818fa149bcd070131d6b04e5d97e2f67d28684/config/ur5_controllers.yaml
# Customization - From: http://answers.gazebosim.org/question/20217/physics-problem-with-simple-movement-of-grasped-object/?answer=20499#post-id-20499
# ONLY MAKE SENSE WITH EFFORTCONTROLLER
  # gains:
  #   bvr_SIM/main_arm_SIM/shoulder_pan_joint: {p: 10000, d: 150, i: 0, i_clamp: 1}
  #   bvr_SIM/main_arm_SIM/shoulder_lift_joint: {p: 50000, d: 150, i: 10, i_clamp: 50}
  #   bvr_SIM/main_arm_SIM/elbow_joint: {p: 50000, d: 150, i: 1, i_clamp: 25}
  #   bvr_SIM/main_arm_SIM/wrist_1_joint: {p: 100, d: 5, i: 0, i_clamp: 1}
  #   bvr_SIM/main_arm_SIM/wrist_2_joint: {p: 75, d: 2, i: 0, i_clamp: 1}
  #   bvr_SIM/main_arm_SIM/wrist_3_joint: {p: 25, d: 1, i: 0, i_clamp: 1}
  # END Customization - From: http://answers.gazebosim.org/question/20217/physics-problem-with-simple-movement-of-grasped-object/?answer=20499#post-id-20499
