#!/usr/bin/env python
import time
import rospy
import actionlib
import math
from control_msgs.msg import *
from trajectory_msgs.msg import *

hosting_robot_prefix = "bvr_SIM/"
ur5_e_robot_prefix = "main_arm_SIM/"
ur5e_arm_prefix = hosting_robot_prefix + ur5_e_robot_prefix
#ur5e_arm_controller_topic = ur5_e_robot_prefix + "scaled_pos_traj_controller/follow_joint_trajectory"
ur5e_arm_controller_topic = ur5_e_robot_prefix + "compliance_controller/follow_joint_trajectory"

JOINT_NAMES = [ur5e_arm_prefix+'shoulder_pan_joint',
               ur5e_arm_prefix+'shoulder_lift_joint',
               ur5e_arm_prefix+'elbow_joint',
               ur5e_arm_prefix+'wrist_1_joint',
               ur5e_arm_prefix+'wrist_2_joint',
               ur5e_arm_prefix+'wrist_3_joint']

shoulder_pan_home = 0.0 #1.0*math.pi/2
shoulder_lift_home = -1.5*math.pi/6
elbow_home = -4.5*math.pi/6
wrist_1_home = -0.15*math.pi/2
wrist_2_home = 1.0*math.pi/2
wrist_3_home = 0.0*math.pi/2

Q1 = [shoulder_pan_home                    ,shoulder_lift_home                     ,elbow_home                     ,wrist_1_home                    ,wrist_2_home                    ,wrist_3_home]
Q2 = [shoulder_pan_home -1.25*math.pi/6    ,shoulder_lift_home -1.50*math.pi/6     ,elbow_home +1.50*math.pi/6     ,wrist_1_home                    ,wrist_2_home +0*1.5*math.pi/6   ,wrist_3_home]
Q3 = [shoulder_pan_home                    ,shoulder_lift_home -0.5*1.50*math.pi/6 ,elbow_home +2*1.50*math.pi/6   ,wrist_1_home -0.85*math.pi/2    ,wrist_2_home                    ,wrist_3_home]
Q4 = [shoulder_pan_home +1.25*math.pi/6    ,shoulder_lift_home -0.75*math.pi/6     ,elbow_home +1.50*math.pi/6     ,wrist_1_home                    ,wrist_2_home -0*1.5*math.pi/6   ,wrist_3_home]
Q5 = Q1
slowdown = 4.0

client = None

def move():
    g = FollowJointTrajectoryGoal()
    g.trajectory = JointTrajectory()
    g.trajectory.joint_names = JOINT_NAMES
    g.trajectory.points = [
        JointTrajectoryPoint(positions=Q1, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*1.0)),
        JointTrajectoryPoint(positions=Q2, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*2.0)),
        JointTrajectoryPoint(positions=Q3, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*3.0)),
        JointTrajectoryPoint(positions=Q4, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*4.0)),
        JointTrajectoryPoint(positions=Q5, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*5.0))]
    client.send_goal(g)
    try:
        client.wait_for_result()
    except KeyboardInterrupt:
        client.cancel_goal()
        raise

def move_disordered():
    order = [4, 2, 3, 1, 5, 0]
    g = FollowJointTrajectoryGoal()
    g.trajectory = JointTrajectory()
    g.trajectory.joint_names = [JOINT_NAMES[i] for i in order]
    q1 = [Q1[i] for i in order]
    q2 = [Q2[i] for i in order]
    q3 = [Q3[i] for i in order]
    q4 = [Q4[i] for i in order]
    q5 = [Q4[i] for i in order]
    g.trajectory.points = [
        JointTrajectoryPoint(positions=q1, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*1.0)),
        JointTrajectoryPoint(positions=q2, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*2.0)),
        JointTrajectoryPoint(positions=q3, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*3.0)),
        JointTrajectoryPoint(positions=q4, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*4.0)),
        JointTrajectoryPoint(positions=q5, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*5.0))]
    client.send_goal(g)
    client.wait_for_result()

def move_repeated():
    g = FollowJointTrajectoryGoal()
    g.trajectory = JointTrajectory()
    g.trajectory.joint_names = JOINT_NAMES

    d = slowdown*2.0
    g.trajectory.points = []
    for i in range(10):
        g.trajectory.points.append(
            JointTrajectoryPoint(positions=Q1, velocities=[0]*6, time_from_start=rospy.Duration(d)))
        d += slowdown*1
        g.trajectory.points.append(
            JointTrajectoryPoint(positions=Q2, velocities=[0]*6, time_from_start=rospy.Duration(d)))
        d += slowdown*1
        g.trajectory.points.append(
            JointTrajectoryPoint(positions=Q3, velocities=[0]*6, time_from_start=rospy.Duration(d)))
        d += slowdown*1
        g.trajectory.points.append(
            JointTrajectoryPoint(positions=Q4, velocities=[0]*6, time_from_start=rospy.Duration(d)))
        d += slowdown*1
        g.trajectory.points.append(
            JointTrajectoryPoint(positions=Q5, velocities=[0]*6, time_from_start=rospy.Duration(d)))
        d += slowdown*1
    client.send_goal(g)
    try:
        client.wait_for_result()
    except KeyboardInterrupt:
        client.cancel_goal()
        raise

def move_interrupt():
    g = FollowJointTrajectoryGoal()
    g.trajectory = JointTrajectory()
    g.trajectory.joint_names = JOINT_NAMES
    g.trajectory.points = [
        JointTrajectoryPoint(positions=Q1, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*1.0)),
        JointTrajectoryPoint(positions=Q2, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*2.0)),
        JointTrajectoryPoint(positions=Q3, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*3.0)),
        JointTrajectoryPoint(positions=Q4, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*4.0)),
        JointTrajectoryPoint(positions=Q4, velocities=[0]*6, time_from_start=rospy.Duration(slowdown*5.0))]

    client.send_goal(g)
    time.sleep(2.0)
    print "Interrupting"
    client.send_goal(g)
    try:
        client.wait_for_result()
    except KeyboardInterrupt:
        client.cancel_goal()
        raise

def main():
    global client
    try:
        rospy.init_node("ur5_e_arm_move", anonymous=True, disable_signals=True)
        client = actionlib.SimpleActionClient(ur5e_arm_controller_topic, FollowJointTrajectoryAction)
        print "Waiting for ur5_e_arm server..."
        client.wait_for_server()
        print "Connected to ur5_e_arm server"
        move()
    except KeyboardInterrupt:
        rospy.signal_shutdown("KeyboardInterrupt")
        raise

if __name__ == '__main__': main()
